version: "3.8"

services:
  db:
    image: postgres:15
    container_name: appointment-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: appointmentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: appointment-web
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password123@db:5432/appointmentdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
